### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by domenmerhar** [domenmerhar/Resi-Amazonski-Pragozd#1]
- [x] ability for allies to stop grey areas from being destroyed
- [x] save sorted scores 
- [x] save on quit
- [x] replay
- [x] main menu
- [x] main menu: high scores
- [x] main menu: username
- [x] game over
- [x] game complete
- [ ] enemy kill collisions
- [ ] continue
